# Generated by Django 3.1.7 on 2021-06-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoProduct',
        ),
    ]
