# Generated by Django 3.1.7 on 2021-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210605_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoproduct',
            name='slug',
            field=models.SlugField(default='man-bag', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
